version: "3"

tasks:
  versatile-apa:
    cmds:
      - typst compile --root versatile-apa versatile-apa/template/main.typ
  dev-versatile-apa:
    cmds:
      - typst watch --root versatile-apa versatile-apa/template/main.typ
