[package]
name = "latex-reborn"
version = "0.1.0"
compiler = "0.13.1"
repository = "https://github.com/jassielof/typst-templates"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "MIT-0"
description = "LaTeX Standard document classes ported to Typst."
keywords = ["UPSA", "Universidad Privada de Santa Cruz de la Sierra", "Bolivia"]
categories = ["report", "paper", "book"]
disciplines = []
exclude = ["*.pdf", "reference"]

[template]
path = "template"
entrypoint = "report.typ"
thumbnail = "thumbnail.png"
