name: Typst Template Issue
description: Report an issue with one of the Typst templates
assignees: "jassielof"
body:
  - type: markdown
    attributes:
      value: |
        # Typst Template Issue

        Thank you for taking the time to report an issue with one of our Typst templates!

        **Important Notes:**
        - After submitting, please add the appropriate template label.
        - If you're using a template from Typst Universe, be sure to specify the package version.

  - type: dropdown
    id: typst-template
    attributes:
      label: Template
      description: Which template are you having issues with?
      multiple: false
      options:
        - Versatile APA
        - LaTeX Standard Class
        - UPSA Bolivia (Estudio de Factibilidad)
        - UPSA Bolivia (Tesis)
    validations:
      required: true

  - type: dropdown
    id: template-source
    attributes:
      label: Template Source
      description: Where did you get the template from?
      options:
        - Typst Universe
        - GitHub Repository
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: If from Typst Universe, specify the package version (e.g., @preview/versatile-apa:0.1.0)
      placeholder: "@preview/template-name:x.y.z"

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you experiencing?
      options:
        - Compilation Error
        - Visual/Formatting Problem
        - Missing Feature
        - Documentation Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Provide a clear and detailed description of the issue
      placeholder: "Describe what happened and what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Add the following code '...'
        3. Compile the document
        4. See the error

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: If applicable, share the relevant code snippet that causes the issue
      render: typst
      placeholder: |
        #show heading: it => {
          set block(spacing: 0.65em)
          set text(font: "New Computer Modern")
          it
        }

  - type: input
    id: typst-version
    attributes:
      label: Typst Version
      description: What version of Typst are you using?
      placeholder: "e.g., 0.10.0"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop images here"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant to the issue
      placeholder: "Add any other context about the problem here"
