#:schema file:///home/jassielof/GitHub/jassielof/schemastore-typst/src/schemas/json/typst.json
[package]
name = "acm-suite"
version = "2.12.0"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "MIT-0"
description = "ACM template suite port of the LaTeX acm-article template."
keywords = [
  "ACM",
  "Association for Computing Machinery",
  "Computer Science",
  "Research",
  "Academic Writing",
]
categories = ["paper", "report"]
disciplines = [
  "computer-science",
  "agriculture",
  "engineering",
  "physics",
  "law",
  "philosophy",
]

[template]
path = "template"
entrypoint = "sig-conf.typ"
thumbnail = "thumbnail.png"


# [package]
# name = "versatile-acm"
# version = "2.12.0"
# compiler = "0.13.1"
# entrypoint = "lib.typ"
# repository = "https://github.com/jassielof/typst-templates"
# authors = ["Jassiel Ovando <@jassielof>"]
# license = "MIT-0"
# description = "ACM template port of the LaTeX acm-article template."
# keywords = [
#     "ACM",
#     "Association for Computing Machinery",
#     "Computer Science",
#     "Research",
#     "Academic Writing",
# ]
# categories = ["paper", "report"]
# disciplines = ["computer-science", "engineering"]
