name: Typst Build

on:
  push:
    branches:
      - main
    paths:
      - "versatile-apa/**"
      - "upsa-bo/**"
      - ".github/workflows/typst.yml"
  pull_request:
    branches:
      - main
    paths:
      - "versatile-apa/**"
      - "upsa-bo/**"
      - ".github/workflows/typst.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up Typst
        run: brew install typst

      - name: Set up fonts
        run: |
          brew install --cask font-cascadia-code
          brew install --cask font-libertinus
          brew install --cask font-computer-modern
          brew install --cask font-new-computer-modern
          sudo fc-cache -f -v

      - name: Cache fonts
        uses: actions/cache@v3
        with:
          path: ~/.local/share/fonts
          key: ${{ runner.os }}-fonts-${{ hashFiles('**/*.ttf', '**/*.otf') }}

      - name: Versatile APA
        run: typst compile --root . versatile-apa/template/main.typ

      - name: ACM Suite
        run: |
          typst compile --root . acm-suite/template/sig-con.typ
          typst compile --root . acm-suite/template/manuscript.typ

      - name: UPSA Bolivia - Estudio de Factibilidad
        run: typst compile --root . upsa-bo/estudio-de-factibilidad/template/estudio-de-factibilidad.typ

      - name: UPSA Bolivia - Tesis
        run: typst compile --root . upsa-bo/tesis/template/tesis.typ
